language: generic
git:
  submodules: false
before_install:
  - git submodule update --init --remote --recursive
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools  
  - pip3 install --user rsa
  - pip3 install --user wheel
  - sudo apt-get install pandoc
  - echo -e "machine github.com\n  login xq4\n  password $CI_USER_PASSWORD" > ~/.netrc
  - chmod 600 ~/.netrc
deploy:
  - provider: script
    script: ./release.sh
